# Úkoly

## Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [4]:
import numpy as np

a = np.arange(0, 11, 1)
print(a)

b = np.random.rand(3, 3)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10]
[[0.85895576 0.75888164 0.28357916]
 [0.58414757 0.90016234 0.45231451]
 [0.94340257 0.02421193 0.85561017]]



1. Vyberte z pole `a` třetí a čtvrtý prvek.


In [6]:
print(a[2:4])

[2 3]



2. Vyberte z pole `a` všechny sudá čísla.


In [7]:
print(a[::2])

[ 0  2  4  6  8 10]



3. Obraťte vektor `a` (první prvek se stane posledním).


In [13]:
print(a[::-1])

[10  9  8  7  6  5  4  3  2  1  0]



5. Vyberte z pole `b` druhý řádek.


In [14]:
print(b[1,:])

[0.58414757 0.90016234 0.45231451]



6. Vyberte z pole `b` diagonální prvky.


In [15]:
print(np.diag(b))

[0.85895576 0.90016234 0.85561017]



7. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.


In [16]:
b[1, 0] = 100
print(b)

[[8.58955757e-01 7.58881637e-01 2.83579158e-01]
 [1.00000000e+02 9.00162337e-01 4.52314511e-01]
 [9.43402575e-01 2.42119270e-02 8.55610169e-01]]



8. Vyberte z pole `b` všechny prvky větší než 5.


In [22]:
print(b[b>5])

[100.]



9. Vytvořte masku pro pole `b`, která bude True pro všechny prvky menší než 3.


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


10. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.





## View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.



1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.



3. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?



4. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.



5. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?



6. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.



7. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.



8. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?



9. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Jak je to s pamětí, jedná se o kopii nebo o "array view" ověřte pomocí atributu base.




## Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


2. Vezměme náhodnou matici 10x2 představující kartézské souřadnice, převeďte je na polární souřadnice.


3. Vzhledem ke dvěma polím X a Y zkonstruujte Cauchyho matici C (Cij =1/(xi - yj)).


4. Uvažujme náhodný vektor o tvaru (100,2) představující souřadnice, najděte vzdálenosti bod po bodu.


5. Ověřte empiricky na náhodné matici, že platí $(AB)^T = B^T A^T$


6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$ $$(uv)_{ij} = u_iv_j$$ pomocí `newaxis`. Zkontrolujte s `np.outer(u, v)`


7. Vypočítejte hodnost matice o velikosti 5x6 naplněnou hodnotami 0, 1, 2, 3 ... . Byly by jste schopni zdůvodnit proč je hodnost taková jaká je?



## Funkce nad poli
1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.


2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.



3. Uvažujme celočíselný vektor Z, které z těchto výrazů jsou platné?
   ```python
   Z**Z
   2 << Z >> 2
   Z <- Z
   1j*Z
   Z/1/1
   Z<Z>Z
   ```



4. Jaký je výsledek následujícího výrazu? 
   ```python
   0 * np.nan
   np.nan == np.nan
   np.inf > np.nan
   np.nan - np.nan
   np.nan in set([np.nan])
   0.3 == 3 * 0.1
   ```


5. Jaké jsou výsledky následujících výrazů?
   ```python
   np.array(0) / np.array(0)
   np.array(0) // np.array(0)
   np.array([np.nan]).astype(int).astype(float)
   ```



6. Jak najít společné (stejné) hodnoty mezi dvěma poli? 



7. Jak vypočítat ((A+B)*(-A/2)) přímo v poli (bez kopírování)?




8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.



9. Vezměme daný vektor, jak přidat 1 ke každému prvku indexovanému druhým vektorem (dejte pozor na opakované indexy)? 

