# Úkoly

## Ndarray
1. Jak zjistit velikost paměti libovolného pole. Vyzkoušejte na `a = np.array([1, 2, 3])`. Ozkoušejte s různou specifikací datového typu (`dtype` např. `np.int32`, `np.float64`, `np.complex128`).


In [140]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
print(a.nbytes)
a = np.array([1, 2, 3], dtype=np.float64)
print(a.nbytes)
a = np.array([1, 2, 3], dtype=np.complex128)
print(a.nbytes)
a = np.array([1, 2, 3], dtype=np.complex256)
print(a.nbytes)

12
24
48
96



2. Zjistěte rozměry, velikost v jednotlivých rozměrech a celkový počet prvků v poli `a`.


In [141]:
print(f"Dimensions = {a.ndim}")
print(f"Size in all dimensions = {a.shape}")
print(f"Total number of elements = {a.size}")


Dimensions = 1
Size in all dimensions = (3,)
Total number of elements = 3



3. Zjistěte typ prvků v poli `a` a velikost jednoho prvku v bajtech.


In [142]:
print(f"Type = {a.dtype}")
print(f"Element size = {a.itemsize}")

Type = complex256
Element size = 32



4. Vytvořte NumPy pole s názvem `b` o stejných rozměrech jako `a`, ale s typem `np.float32`.


In [143]:
b = np.ndarray(shape=a.shape, dtype=np.float32)
b

array([1.e-45, 3.e-45, 4.e-45], dtype=float32)


5. Přetypujte pole `a` na typ `np.float32` a uložte do pole `c`.


In [144]:
c = a.astype(np.float32)
c

/tmp/ipykernel_6460/3829406383.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  c = a.astype(np.float32)


array([1., 2., 3.], dtype=float32)


6. Vytvořte pole `d` s typem `np.datetime64` a uložte do něj datum "2023-12-01".


In [145]:
d = np.array(["2023-12-01"], dtype=np.datetime64)
d

array(['2023-12-01'], dtype='datetime64[D]')


7. Vytvořte pole `e` s typem složeným ze dvou sloupců: `int32` a `string_` s maximální délkou 10 znaků.


In [146]:
dt = np.dtype([("integer", np.int32), ("string", np.string_, 10)])
e = np.ndarray(shape=(3), dtype=dt)
e

array([(1075881911, b'\xe0U'), (  84934656, b'v\x01I\x7f'),
       (         0, b'`')], dtype=[('integer', '<i4'), ('string', 'S10')])


8. Naplňte pole `e` hodnotami: `[(1, "a"), (2, "b"), (3, "c")]`.


In [147]:
e = np.array([(1, "a"), (2, "b"), (3, "c")], dtype=dt)
print(e)

[(1, b'a') (2, b'b') (3, b'c')]



9. Změňte hodnotu druhého prvku v druhém sloupci pole `e` na "hello".


In [148]:
e[1]["string"] = "hello"
print(e)

[(1, b'a') (2, b'hello') (3, b'c')]


## Vytváření polí
1. Vytvořte matici samých jedniček o rozměrech 3x3. Vypište všechny její prvky.

In [149]:
A = np.ones((3,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


2. Vytvořte vektor s hodnotami od 10 do 49.


In [150]:
v = np.arange(10, 50, 1)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Vytvořte pole 3x4 typu `bool` se všemi prvky `True`.


In [151]:
B = np.full((3,4), True)
print(B)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


4. Vytvořte matici 3x3 s hodnotami od 0 do 8.


In [152]:
values = np.arange(0, 9, 1)
M = values.reshape((3,3))
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Vytvořte jednotkovou matici 3x3.


In [153]:
I = np.diagflat([1, 1, 1])
print(I)
# or maybe this could work too
I = np.eye((3))
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


6. Vytvořte pole 3x3x3 s náhodnými hodnotami.


In [154]:
R = np.random.rand(3,3,3)
print(R)

[[[0.19318595 0.8654034  0.10983944]
  [0.90375259 0.31511235 0.18792977]
  [0.83971637 0.70345736 0.45866214]]

 [[0.42390238 0.70793565 0.46755018]
  [0.77521324 0.16078588 0.25560714]
  [0.53298058 0.67616577 0.58080819]]

 [[0.16456848 0.7198067  0.52520082]
  [0.87666253 0.83100689 0.23178925]
  [0.84524438 0.64549735 0.45544426]]]


7. Vytvořte 2D pole s 1 na okraji a 0 uvnitř.


In [155]:
C = np.ones((4, 6))
C[1:-1, 1:-1] = 0
print(C)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


8. Jak přidat okraj (vyplněný nulami) kolem existujícího pole?


In [156]:
m, n = C.shape
new_shape = (m + 2, n + 2)
C_new = np.zeros(new_shape)
C_new[1:-1, 1:-1] = C
print(C_new)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


9. Vytvořte matici 5x5 kde jediné nenulová prvky jsou [1, 2, 3, 4] pod hlavní diagonálou (nápověda - podívejte se na nápovědu funkce `diagflat`).
```
0 0 0 0 0
1 0 0 0 0
0 2 0 0 0
0 0 3 0 0 
0 0 0 4 0
```


In [157]:
#help(np.diagflat)
print(np.diagflat([1, 2, 3, 4], -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


10. Z pole 8x8 samých nul vyvořte pomocí řezů co nejelegantnějším způsobem 8x8 matici, která vypadá jako šachovnice.
```
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
```


In [158]:
X = np.zeros((8, 8))
X[0::2, 1::2] = 1
X[1::2, 0::2] = 1
print(X)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


11. Vytvořte šachovnicovou matici 8x8 pomocí funkce "tile".


In [159]:
pattern = [[1, 0], [0, 1]]
X = np.tile(pattern, (4, 4))
print(X)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


12. Vytvořte vektor velikosti 10 s hodnotami v rozsahu od 0 do 1 (obě hodnoty vyloučeny).


In [160]:
v = np.linspace(0, 1, 12)[1:-1]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


13. Vytvořte strukturované pole s koordináty x a y pokrývající oblast [0,1]x[0,1].


In [161]:
x = np.linspace(0, 1, 100)
y = np.linspace(0, 1, 100)
X, Y = np.meshgrid(x, y)

A = np.zeros((100*100,), dtype=[('x', float), ('y', float)])
A['x'] = X.flatten()
A['y'] = Y.flatten()

print(A)
#?? not really sure about this

[(0.        , 0.) (0.01010101, 0.) (0.02020202, 0.) ... (0.97979798, 1.)
 (0.98989899, 1.) (1.        , 1.)]


## Numpy a práce se soubory

1. Jak přečíst následující soubor?
   ```
   1, 2, 3, 4, 5
   6, , , 7, 8
    , , 9,10,11
   ```





In [162]:
%%writefile test_data.csv
1, 2, 3, 4, 5
6, , , 7, 8
 , , 9,10,11

Overwriting test_data.csv


In [163]:
data = np.genfromtxt("test_data.csv", delimiter=",")
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


2. Vytvořte tři náhodné matice 5x5 a uložte je do souboru pomocí formátu hdf5.

In [164]:
import h5py

A1 = np.random.rand(5, 5)
A2 = np.random.rand(5, 5)
A3 = np.random.rand(5, 5)

with h5py.File("matrices.h5", "w") as hdf5_file:
    hdf5_file.create_dataset("A1", data=A1)
    hdf5_file.create_dataset("A2", data=A2)
    hdf5_file.create_dataset("A3", data=A3)


3. Načtěte soubor z předchozího úkolu, zobrazte obsah každé matice a zjistěte jejich rozměry.

In [165]:
with h5py.File("matrices.h5", "r") as hdf5_file:
    #data_hdf5 = hdf5_file["A1"]
    a1 = hdf5_file["A1"][:]
    a2 = hdf5_file["A2"][:]
    a3 = hdf5_file["A3"][:]

    print(a1)
    print(a1.shape)
    print(a2)
    print(a2.shape)
    print(a3)
    print(a3.shape)

[[0.16297382 0.97112653 0.05334092 0.92104829 0.07283276]
 [0.73883183 0.34967583 0.25964187 0.28241668 0.14071944]
 [0.58515007 0.54606803 0.52182398 0.86852041 0.81537854]
 [0.38879923 0.40503433 0.99314365 0.24461169 0.53753671]
 [0.0749763  0.57916405 0.2643636  0.65670446 0.67684656]]
(5, 5)
[[0.82159041 0.92261434 0.51762746 0.92135283 0.51832195]
 [0.11558676 0.94728422 0.2985888  0.44572902 0.56733105]
 [0.08303799 0.3549355  0.41381968 0.80030617 0.80117956]
 [0.86807586 0.97296464 0.14810479 0.1965884  0.49002484]
 [0.13965508 0.37453207 0.07849915 0.26399138 0.34622384]]
(5, 5)
[[0.49851954 0.98292963 0.46068131 0.52595465 0.77803832]
 [0.36483721 0.65236433 0.64115173 0.39142901 0.91803944]
 [0.52486112 0.64030797 0.82135005 0.28186308 0.86842525]
 [0.50920833 0.12873234 0.38121123 0.23281283 0.67491052]
 [0.05484645 0.40045331 0.35546933 0.86299824 0.51770593]]
(5, 5)
